# kasesag.me hugo page config

baseURL = "https://kasesag.me/"
author = "kasesag"
title = "kasesag's personal home page"
copyright = "made with â™¥ by kasesag Â© 2022" 
languageCode = "en"
DefaultContentLanguage = "en"
pluralizelisttitles = false
summaryLength = 24

[params]
author = "kasesag"
description = "Hello there! I'm kasesag and this is my personal home page."
# Header
mainTitle = "kasesag."
mainDescription = "ðŸ’¾ don't forget to insert a floppy before booting!"

[permalinks]
blog = "/:year/:month/:slug/"

[menu]
    [[menu.nav]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

    [[menu.nav]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
    # [[menu.nav]]
    # identifier = "personal-projects"
    # name = "Projects"
    # url = "/projects"
    # weight = 3


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
    [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
	[markup.goldmark.renderer]
	unsafe = true