# kasesag.me hugo page config

baseURL = "https://kasesag.me/"
author = "kasesag"
title = "kasesag's personal home page"
copyright = "made with â™¥ by kasesag Â© 2022" 
languageCode = "en"
DefaultContentLanguage = "en"
pluralizelisttitles = false
summaryLength = 24

[params]
author = "kasesag"
description = "Hello there! I'm kasesag and this is my personal home page."
    
    [params.header]
    mainTitle = "kasesag."
    mainDescription = "ğŸ’¾ don't forget to insert a floppy before booting!"
    altDescriptions = [
        "ğŸ’¾ don't forget to insert a floppy before booting!",
        "welcome to my personal home page! ğŸ‘‹",
        "shh, rainbow floppy inside ! ğŸ’¾",
        "Being Not Straight ğŸ³ï¸â€ğŸŒˆ",
        "Dreams. Fantasies. Ideas. Where do they go when life brings you tumbling back to the now?",
        "Ğ¡Ğ›ĞĞ’Ğ Ğ£ĞšĞ ĞĞ‡ĞĞ†! ğŸ‡ºğŸ‡¦",
    ]

[permalinks]
blog = "/:year/:month/:slug/"

[menu]
    [[menu.nav]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

    [[menu.nav]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
    # [[menu.nav]]
    # identifier = "personal-projects"
    # name = "Projects"
    # url = "/projects"
    # weight = 3


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
    [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
	[markup.goldmark.renderer]
	unsafe = true